name: Test and deploy to Expo hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 15.14.0
      - name: Run unit and integration tests
        run: yarn test

  publish_expo_server:
    needs: [test]
    environment: 
      name: Development
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.8.5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
      - name: Expo GitHub Action
        uses: expo/expo-github-action@6.0.0
        with:
          username: ${{ secrets.EXPO_USERNAME }}
          password: ${{ secrets.EXPO_PASSWORD }}
      - name: Deploy to Expo hosting
        run: expo publish
